version: '3.3'

services:
  app:
    image: drugrepochat
    container_name: drugrepochat
    links:
      - "db"
    build: .
    ports:
      - ${port_mapping}

  db:
    container_name: drugrepochatdb
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${root_pw}

volumes:
  desmond2-eval-volume: